services:
  mongodb:
    image: mongo:4.4.30-focal
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

  cwmp:
    build:
      context: .
    image: local/genieacs:1.2.16
    restart: unless-stopped
    command: ["genieacs-cwmp"]
    depends_on:
      mongodb:
        condition: service_started
    environment: &genieacs-env
      SERVICE_URL_CWMP:
      SERVICE_URL_CWMP_7547:
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://mongodb/genieacs
      GENIEACS_UI_JWT_SECRET: ${GENIEACS_UI_JWT_SECRET:-change-me-before-production}
      GENIEACS_EXT_DIR: /opt/genieacs/ext
      NODE_OPTIONS: --enable-source-maps
      
      
    ports:
      - "${GENIEACS_CWMP_HOST_PORT:-7547}:7547"
    volumes:
      - genieacs-ext:/opt/genieacs/ext

  nbi:
    image: local/genieacs:1.2.16
    restart: unless-stopped
    command: ["genieacs-nbi"]
    depends_on:
      mongodb:
        condition: service_started
      cwmp:
        condition: service_started
    environment: *genieacs-env
    ports:
      - "${GENIEACS_NBI_HOST_PORT:-7557}:7557"
    volumes:
      - genieacs-ext:/opt/genieacs/ext

  fs:
    image: local/genieacs:1.2.16
    restart: unless-stopped
    command: ["genieacs-fs"]
    depends_on:
      mongodb:
        condition: service_started
      cwmp:
        condition: service_started
    environment: *genieacs-env
    ports:
      - "${GENIEACS_FS_HOST_PORT:-7567}:7567"
    volumes:
      - genieacs-ext:/opt/genieacs/ext

  ui:
    image: local/genieacs:1.2.16
    restart: unless-stopped
    command: ["genieacs-ui"]
    depends_on:
      mongodb:
        condition: service_started
      cwmp:
        condition: service_started
      nbi:
        condition: service_started
      fs:
        condition: service_started
    environment: *genieacs-env
    ports:
      - "${GENIEACS_UI_HOST_PORT:-3000}:3000"
    volumes:
      - genieacs-ext:/opt/genieacs/ext

volumes:
  mongodb-data:
  genieacs-ext:
